import typer

n1=input('escreva algo:')
print('informações sobre oque foi escrito')
print('se e um numero')
print(n1.isnumeric())
print('        ^        ')
print('se é alfabetizado')
print(n1.isalpha())
print("        ^ ")
print('se comtem acento')
print(n1.isalnum())
print('        ^')
print('se esta em letras maiusculas')
print(n1.isupper())
print('        ^')
print('se esta em letras minusculas')
print(n1.islower())
print('        ^')
print('se é alfanumerico')
print(n1.isalnum())
print('        ^')
print('se e composto por espaços')
print(n1.isspace())
print('        ^')
print('e tipo primitivo')
print(type(n1) )
print('        ^')
print('se esta capitalizada')
print(n1.istitle())
print('processo concluido')